[package]
name = "bittorrent-from-scratch"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
hex = "0.4.3"
log = "0.4.27"
percent-encoding = "2.3.2"
reqwest = "0.12.23"
sha1 = "0.10.6"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
